sudo: required

language: go

go:
- "1.10"

services:
- docker

cache:
  directories:
  - tmp-build
  - $GOPATH/bin
  - $GOPATH/pkg

env:
  global:
  - LIBRDKAFKA_VERSION=v0.11.4
  - PKG_CONFIG_PATH="$GOPATH/src/github.com/blendle/go-streamprocessor/tmp-build/$LIBRDKAFKA_VERSION/lib/pkgconfig"
  - LD_LIBRARY_PATH="$GOPATH/src/github.com/blendle/go-streamprocessor/tmp-build/$LIBRDKAFKA_VERSION/lib"
  - DYLD_LIBRARY_PATH="$GOPATH/src/github.com/blendle/go-streamprocessor/tmp-build/$LIBRDKAFKA_VERSION/lib"
  - PATH="$PATH:$GOPATH/bin"
  - DOCKER_COMPOSE_VERSION=1.21.0

before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- script/cisetup

install: script/setup
script: script/test
