version: '2'
services:
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
    - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 100
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  pubsub:
    image: bigtruedata/gcloud-pubsub-emulator:latest # no non-latest tag available
    ports:
    - "8538:8538"

  zookeeper:
    image: wurstmeister/zookeeper:latest # no non-latest tag available
    ports:
    - "2181:2181"
