[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  version = "v0.11.6"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  revision = "dd1402a4d99de9ac2f396cd6fcb957bc2c695ec1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "8ccf5352a842c034b1a69f28c863aff9b1cdb116"
