[[constraint]]
  name = "github.com/DATA-DOG/godog"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.15.0"

[[constraint]]
  name = "github.com/bsm/sarama-cluster"
  version = "v2.1.11"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7"
