#!/bin/sh

# script/tests/go-test-race: Run benchmark tests

set -e

cd "$(dirname "$0")/../.."

[ -z "$CI" ] || cd "$GOPATH/src/github.com/blendle/go-streamprocessor"

go test -race $(glide nv) -kafka
