#!/bin/sh

# script/tests/go-test-race: Run benchmark tests

set -aeu

cd "$(dirname "$0")/../.."

[ -z "$CI" ] || {
  cd "$GOPATH/src/github.com/blendle/go-streamprocessor"
  GOPATH=/home/jenkins/go
}

TERM=xterm
godog --random --strict --tags ~@wip "$@"
