#!/bin/sh

# script/tests/gometalinter: Run linters and static analysis

set -e

cd "$(dirname "$0")/../.."

[ -z "$CI" ] || {
  cd "$GOPATH/src/github.com/blendle/go-streamprocessor"
  export GOPATH=/home/jenkins/go
}

matches=$(grep \
  --ignore-case \
  --recursive \
  --exclude-dir vendor \
  '^// [a-z]* \.\.\.$' . || true)

if [ -n "$matches" ]; then
  echo >&2 "Invalid code comments detected:"
  echo >&2
  echo >&2 "$matches"
  echo >&2
  exit 1
fi

gometalinter \
  --vendor \
  --tests \
  --aggregate \
  --deadline=300s \
  --vendored-linters \
  --exclude='error return value not checked.*(Close|Log|Print|Write).*\(errcheck\)$' \
  --exclude='.*_test\.go:.*error return value not checked.*\(errcheck\)$' \
  --exclude='step_test\.go:.*is unused.*\(megacheck\)$' \
  --enable-all \
  --disable=gotype \
  --disable=gas \
  --disable=lll \
  --disable=gocyclo \
  --disable=dupl \
  ./...
