#!/bin/sh

# script/tests/gometalinter: Run linters and static analysis

set -e

cd "$(dirname "$0")/../.."

matches=$(find . \( -name vendor -prune \) \
  -o \( -type f -name '*' \) \
  -exec grep -i '^// [a-z]* \.\.\.$' {} \; || true)

if [ -n "$matches" ]; then
  echo >&2 "Invalid code comments detected:"
  echo >&2
  echo >&2 "$matches"
  echo >&2
  exit 1
fi

# --warn-unmatched-nolint, disabled for now, see: https://git.io/vpGor
gometalinter \
  --vendor \
  --tests \
  --aggregate \
  --sort=line \
  --deadline=300s \
  --vendored-linters \
  --enable-all \
  --line-length=100 \
  --cyclo-over=11 \
  --disable=dupl \
  --disable=testify \
  --disable=test \
  --disable=gochecknoglobals \
  --linter='lll:lll -e func -g -l {maxlinelength}:PATH:LINE:MESSAGE' \
  "${@:-./...}"
