#!/bin/sh

# script/bootstrap: Install project dependencies.

set -e

cd "$(dirname "$0")/.."

command -v dep >/dev/null 2>&1 || {
  os=$(uname -s | awk '{print tolower($0)}')
  curl -L "https://github.com/golang/dep/releases/download/v0.3.1/dep-$os-amd64" > /usr/local/bin/dep
  chmod +x /usr/local/bin/dep
}

command -v gometalinter >/dev/null 2>&1 || go get -u github.com/alecthomas/gometalinter
command -v godog >/dev/null 2>&1 || go get -u github.com/DATA-DOG/godog/cmd/godog
gometalinter --install --update
