#!/bin/sh

# script/bootstrap: Install project dependencies.

set -e

cd "$(dirname "$0")/.."

os=$(uname -s | awk '{print tolower($0)}')

if [ -n "$CI" ] || ! command -v shellcheck >/dev/null 2>&1; then
  if [ "$os" = "darwin" ]; then
    echo >&2 "You need to install shellcheck before continuing."
  fi

  tmp=$(mktemp -d)
  curl -Ls "https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz" |
    tar xJf - --strip 1 -C "$tmp"

  mkdir -p "$GOPATH/bin"
  cp "$tmp/shellcheck" "$GOPATH/bin/shellcheck"
  chmod +x "$GOPATH/bin/shellcheck"
fi

if [ -n "$CI" ] || ! command -v shfmt >/dev/null 2>&1; then
  curl -L "https://github.com/mvdan/sh/releases/download/v2.5.0/shfmt_v2.5.0_${os}_amd64" >"$GOPATH/bin/shfmt"

  chmod +x "$GOPATH/bin/shfmt"
fi
