#!/bin/sh

# script/cisetup: Prepare CI for testing.

set -e

cd "$(dirname "$0")/.."

if [ -z "$CI" ]; then
  echo >&2 "\$CI not set, refusing to run $0."
  exit 1
fi

libpath="tmp-build/$LIBRDKAFKA_VERSION"
if [ ! -d "$libpath" ]; then
  dir="$(pwd)"
  rm -rf tmp-build
  mkdir -p "$libpath/librdkafka"
  cd "$libpath/librdkafka"

  curl -sL "https://github.com/edenhill/librdkafka/archive/$LIBRDKAFKA_VERSION.tar.gz" |
    tar -xz --strip-components=1 -f -

  ./configure --prefix="$dir/$libpath"
  make -j
  make install
  cd "$dir"
fi

docker-compose up -d

printf "waiting for Kafka to boot..."
while ! nc -z -w1 127.0.0.1 9092 </dev/null; do
  printf .
  sleep 3
done

echo
