#!/bin/sh

# script/test: Run the test suite and linters.

set -e

cd "$(dirname "$0")/.."

if [ -z "$*" ] && ! nc -z -w1 127.0.0.1 9092 2>/dev/null; then
  echo >&2 "No response received from 127.0.0.1:9092." \
    "Unable to run integration tests."
  echo >&2
  echo >&2 'Running script with "-short ./..." arguments.'
  echo >&2
  echo >&2 'To run integration tests, first run "docker-compose up".'
  echo >&2

  $0 -short ./...
  exit $?
fi

echo "==      shfmt"
script/tests/shfmt

echo "==      shellcheck"
script/tests/shellcheck

echo "==      golangci-lint"
script/tests/golangci-lint

echo "==      go-test"
script/tests/go-test "$@"

if echo "$*" | grep -qv -- "-short"; then
  echo "==      go-test-cover"
  script/tests/go-test-cover "$@"
fi

echo "==      go-test-race"
script/tests/go-test-race "$@"

if [ -z "$CI" ]; then
  echo "==      go-test-bench"
  script/tests/go-test-bench "$@"
fi
