#!/bin/sh

# script/test: Run the test suite and linters.

set -e

cd "$(dirname "$0")/.."

echo "==      gometalinter"
script/tests/gometalinter

echo "==      go-test"
script/tests/go-test

echo "==      go-test-race"
script/tests/go-test-race

echo "==      go-test-bench"
script/tests/go-test-bench
